name: Compile Typst Documents
on: [push]

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile Typst Files
      uses: ammar-ahmed22/compile-typst-action@v1
      with:
        source_paths: 'main.typ'
        output_paths: 'Appunti-di-Meccanica-Analitica.pdf'
    - name: Commit compiled PDFs
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'Compiled Typst to PDF'
